jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: |
          npm run lint || echo "Lint failed"
          tsc --noEmit || echo "Type check failed"

      - run: npm run build

      # مطمئن بشید داکر نصب شده
      - name: Check Docker version
        run: docker --version

      - run: docker build -t test-frontend-app .

      - run: docker run -d -p 8080:80 --name test-container test-frontend-app

      - run: docker ps -a

      - run: sleep 5

      - run: curl -f http://localhost:8080

      - run: docker exec test-container curl -f http://localhost

      - if: failure()
        run: docker logs test-container

      # مرحله پاکسازی کانتینر برای جلوگیری از باقی موندن
      - if: always()
        run: docker rm -f test-container || true
